name: apples-to-apples-daily

on:
  schedule:
    # 7:30 AM America/Chicago = 12:30 UTC during CDT.
    # Weekdays only (Mon–Fri):
    - cron: '30 12 * * 1-5'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4 urllib3

      - name: Scrape + diff
        run: |
          python apples_to_apples_diff.py

      - name: Prepare email body
        id: body
        run: |
          echo 'text<<EOF' >> $GITHUB_OUTPUT
          cat changes.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          secure: true
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          from: ${{ secrets.MAIL_FROM }}
          to: ${{ secrets.MAIL_TO }}${{ secrets.MAIL_TO2 && format(', {0}', secrets.MAIL_TO2) || '' }}
          subject: "OH & Columbia Apples-to-Apples (Weekdays)"
          body: ${{ steps.body.outputs.text }}
          attachments: |
            report.txt
            changes.txt

      - name: Commit snapshots (optional)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv || true
          git commit -m "Daily snapshots: $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push || echo "Nothing to push"
